// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using duplicateVideoFinder;

#nullable disable

namespace duplicateVideoFinder.Migrations
{
    [DbContext(typeof(MetricCacheDbContext))]
    partial class MetricCacheDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("duplicateVideoFinder.MetricCacheEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirectoryPath")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratorId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastWriteUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetricJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetricType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryPath", "GeneratorId", "FilePath")
                        .IsUnique();

                    b.ToTable("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
